version: "3.8"
services:
  web:
    build: .
    ports:
      - "${PORT:-8080}:80" # Use environment variable PORT (default 8080)
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dnr
      MYSQL_USER: dnruser
      MYSQL_PASSWORD: dnrpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
