<?php if ($deliveries): ?>
<section class="reimbursement-card"><h2>Email Delivery</h2><p>Submitted records remain locked regardless of email delivery. SMTP acceptance does not confirm receipt, reading, or payment. Recovery uses the exact original recipients, message, and package for up to 365 days.</p>
<?php if ($request['correction_at']): ?><p class="warning">Correction Recorded <?= reimbursementRequestH($request['correction_at']) ?> UTC: <?= reimbursementRequestH($request['correction_note']) ?>. Messages already sending or accepted cannot be recalled. Coordinate any replacement with the bookkeeper; these expenses remain locked.</p><?php endif; ?>
<div class="reimbursement-table-wrap"><table class="data-table"><thead><tr><th>Recipient</th><th>Delivery Status</th><th>Attempts</th><th>Last Acceptance</th><th>Action</th></tr></thead><tbody>
<?php foreach ($deliveries as $delivery): $approved=$snapshot['deliveries'][(string)$delivery['id']] ?? null; ?>
<tr><td><?= reimbursementRequestH(ucfirst($delivery['recipient_type'])) ?><?= $approved ? ': '.reimbursementRequestH($approved['recipient']) : ' (Original Address Not Retained)' ?></td><td><?= reimbursementRequestH(match($delivery['status']) {'sent'=>'Accepted by SMTP','delivery_uncertain'=>'Needs Review — Delivery Uncertain','processing'=>'Sending','pending'=>'Queued','retry'=>'Retry Scheduled','failed'=>'Failed','cancelled'=>'Cancelled',default=>$delivery['status']}) ?><?php if ($delivery['last_error']): ?><small><?= reimbursementRequestH($delivery['last_error']) ?></small><?php endif; ?></td><td><?= (int)$delivery['attempts'] ?></td><td><?= reimbursementRequestH($delivery['sent_at'] ?? '—') ?></td><td>
<?php if ($canManage && $approved && !$request['correction_at'] && !(int)$request['is_archived'] && in_array($delivery['status'],['failed','sent','delivery_uncertain','cancelled'],true)): ?>
<details><summary><?= $delivery['status']==='failed' ? 'Retry Failed Delivery' : 'Send Another Copy' ?></summary><form method="post" data-confirm="Send the original approved message and package to this recipient again? An accepted or uncertain delivery may already have arrived." data-confirm-title="Send Another Copy?" data-confirm-label="Send Copy"><?= csrfInput() ?><input type="hidden" name="delivery_id" value="<?= (int)$delivery['id'] ?>"><input type="hidden" name="action" value="<?= $delivery['status']==='failed' ? 'retry_delivery' : 'resend_delivery' ?>"><label>Reason<input name="reason" maxlength="1000" required></label><label><input type="checkbox" name="provider_checked" value="1" required> I checked the delivery history<?= $delivery['status']==='delivery_uncertain' ? ' and provider records' : '' ?> and approve sending this copy</label><button class="button-secondary" type="submit">Queue Copy</button></form></details>
<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if ($canManage): ?><details><summary>Record a Correction</summary><p>This preserves the original record and cancels only messages that have not begun sending. It does not recall email or make these expenses available for another request.</p><form method="post" data-confirm="Record this correction and cancel messages that have not begun sending? Expenses remain locked." data-confirm-title="Record Correction?" data-confirm-label="Record Correction"><?= csrfInput() ?><input type="hidden" name="action" value="correction"><label>Correction Reason<textarea name="reason" maxlength="1000" required></textarea></label><button type="submit" class="button-secondary">Record Correction</button></form></details><?php endif; ?>
<?php if ($canManage && $request['correction_at']): ?><details><summary>Resolve Correction</summary><form method="post"><?= csrfInput() ?><input type="hidden" name="action" value="resolve_correction"><label>Resolution Note<textarea name="reason" maxlength="1000" required></textarea></label><p>Record your agreement with the bookkeeper. The original package and expense locks stay unchanged. No email is sent by this action.</p><button type="submit" class="button-secondary">Resolve Correction</button></form></details><?php endif; ?>
</section><?php endif; ?>
<?php if ($events): ?><section class="reimbursement-card"><h2>Request History</h2><ul><?php foreach ($events as $event): ?><li><?= reimbursementRequestH($event['created_at'].' UTC · '.($event['username'] ?? 'System').' · '.ucwords(str_replace('_',' ',$event['action']))) ?><?php if ($event['detail']): ?>: <small><?= reimbursementRequestH($event['detail']) ?></small><?php endif; ?></li><?php endforeach; ?></ul></section><?php endif; ?>
