-- Request history supports administrator review; it is not automatic training data.
CREATE TABLE ai_coach_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at DATETIME(6) NULL,
    user_id INT NULL,
    user_role VARCHAR(16) NOT NULL,
    page_path VARCHAR(80) NOT NULL,
    guided_step VARCHAR(80) NOT NULL DEFAULT '',
    question TEXT NOT NULL,
    conversation_json JSON NOT NULL,
    manual_topic VARCHAR(200) NOT NULL DEFAULT '',
    response_json JSON NULL,
    outcome VARCHAR(24) NOT NULL DEFAULT 'pending',
    duration_ms INT UNSIGNED NULL,
    model_name VARCHAR(100) NOT NULL,
    application_version VARCHAR(100) NOT NULL,
    guidance_revision CHAR(64) NOT NULL,
    review_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed',
    review_notes TEXT NULL,
    corrected_guidance TEXT NULL,
    reviewed_by INT NULL,
    reviewed_at DATETIME(6) NULL,
    review_version INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_coach_request_review (review_status, id),
    INDEX idx_coach_request_user (user_id, id),
    INDEX idx_coach_request_outcome (outcome, id)
);
