/* Capture actual MOED pages from an authenticated, disposable preview.
 * Supply a Playwright module, browser executable, storage state and fixture JSON.
 * Record and message forms are never submitted. Administrator authentication
 * may be submitted to show controls normally hidden behind fresh confirmation.
 */
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'../..');
const base=process.env.DNR_MANUAL_BASE_URL || 'http://127.0.0.1:9087';
if(!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(base))throw Error('Use a loopback disposable preview.');
const f=JSON.parse(fs.readFileSync(process.env.DNR_MANUAL_FIXTURE_JSON || path.join(root,'tmp/pdfs/fixture.json')));
const extra=JSON.parse(fs.readFileSync(process.env.DNR_MANUAL_EXTRA_JSON || path.join(root,'tmp/pdfs/extra.json')));
const out=path.join(root,'docs/user-manual');fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});
const shots=[];
function add(chapter,id,title,route,steps,options={}){shots.push({chapter,id,title,route,steps,...options});}
add(1,"manual","The online manual and navigation","help.php",["Open User Manual near the bottom of the scrollable sidebar. Its 13 chapters match this PDF.", "The logo stays at the top and your profile/sign-out block stays at the bottom; scroll only the menu between them.", "Use the chapter rail, topic cards, or / to search. Use your PDF reader\u2019s Find command for this guide."],{"shell": true});
add(1,'dark','Dark theme','dashboard.php',['Select Dark Theme in the sidebar to use the dark palette.','Select Light Theme to return. The preference is remembered by this browser.'],{action:'dark',shell:true});
add(1,"mobile","Navigation on a phone","dashboard.php",["Tap the menu button to open navigation. The close button, logo, and profile/sign-out block stay in place.", "Scroll the menu between the fixed controls to reach other areas, including User Manual.", "Choose an area, use Close navigation, tap outside the panel, or press Esc."],{"action": "mobile", "shell": true});
add(2,'roles','Preview role permissions','users.php',['Administrators can expand Preview access in the sidebar and select Editor or Reviewer.','Apply changes the menus and effective permissions. Return to Administrator ends the preview.','Preview actions affect application data. Use a separate sample environment when practicing.'],{action:'roles',shell:true});
add(3,'dashboard','Start the day on the Dashboard','dashboard.php',['Scan the summary cards for your workload, the booking pipeline, and items needing review.','Work through My Work, then review upcoming engagements and incomplete details.','Open the linked record to make the change, then return to the Dashboard.']);
add(4,'pipeline','Read and filter the booking board','inquiries.php',['Search requests and narrow by owner, stage, or next action.','Open a card to review the request and its next step.','The default view includes active inquiries and bookings from this month. Other stages remain available in the filter.']);
add(4,'inquiry','Review an inquiry','view_inquiry.php?id='+f.inquiry,['Review the preferred and alternate dates, priority, owner, and next action.','Use Activity, Correspondence, and Tasks to switch the working panel.','Change stage as the request develops; a decline needs a reason and can be reopened.']);
add(4,'inquiry-form','Capture the request and date options','edit_inquiry.php?id='+f.inquiry,['Enter the request title and summary. Choose the organization and primary contact when known.','Record preferred dates, alternate dates, event type, and location.','Choose an owner, priority, source, next action, and due date, then save.']);
add(4,'inquiry-action','Give the inquiry a next action','edit_inquiry.php?id='+f.inquiry,['Keep the next action concrete, such as sending date options or requesting room details.','Set a due date so the pipeline and Dashboard can highlight it.','Use Source Detail for a referral, mailbox, form, or campaign reference.'],{focus:'#inquiry-next-action'});
add(4,'conversion','Convert a qualified inquiry','convert_inquiry.php?id='+f.inquiry,['Review the proposed engagement and any schedule conflicts.','Choose the open inquiry tasks to move; clearing every box moves none.','Carry an unresolved next action forward as a task, or resolve it with a reason.','Acknowledge any availability warnings before confirming the conversion.']);
add(4,'inquiry-email','Write inquiry correspondence','compose_inquiry_email.php?id='+f.inquiry,['Choose Initial response, Request details, Date options, or Proposal follow-up.','Verify the primary contact, then edit the subject and plain-text message.','Queue the message when ready; its signed inquiry marker keeps replies connected.'],{note:'The screenshot preview has mail delivery disabled. The form is shown without sending a message.'});
add(5,'engagement-list','Find an engagement','engagements.php',['Search the complete list, then use lifecycle and current/archive filters.','Sort by organization, date, confirmation, or lifecycle.','Open the event title or View action. Financial closeout is a separate status from planning confirmation.']);
add(5,'engagement','Use the engagement workspace','view_engagement.php?id='+f.event,['Read the event summary and right-side readiness and next-action information.','Switch among Activity, Correspondence, Tasks, Presentations, Contacts, Logistics, and Financials.','Use the nearby routing-marker copy control when continuing a conversation in another email application.']);
add(5,'engagement-form','Edit event details and schedule','edit_engagement.php?id='+f.event,['Choose an active organization and enter the event title and description.','Set valid start and end dates. Choose Other and describe the type when presets do not fit.','Assign a Caller for the initial checklist; later Caller changes do not transfer existing tasks.']);
add(5,'event-contacts','Assign event-specific contact roles','view_engagement.php?id='+f.event,['Open Contacts to see the people assigned to this event and their roles.','In Edit Engagement, add existing contacts or create new people. Assign Primary host, On-site contact, Billing, Travel, and Materials as applicable.','These roles are separate from a contact\'s organization affiliations.'],{tab:'Contacts',focus:'#engagement-workspace'});
add(5,'presentations',"Presentation details and audience resources",'view_engagement.php?id='+f.event,["Open Presentations and review the speaker, title, schedule, duration, and attendance.", "Select View PDF Speaker Notes to open the notes, or Download PPT Slidedeck to save the PowerPoint for a compatible presentation app.", "Select Copy link beneath a QR image to share its web address. Select the image to copy the QR graphic, or PNG/SVG to save it.", "Combined Presentation Statistics covers all codes; Statistics beneath a code opens its own activity."],{tab:'Presentations',focus:'#engagement-workspace'});
add(5,'qr-selection',"Select and order QR codes for a PDF",'view_engagement.php?id='+f.event,["Expand Export Presentation and select View QR Codes PDF. Check one or more codes, or use Select all.", "Drag any row by its handle, whether checked or unchecked. Only checked codes appear in the PDF, in list order from left to right and then top to bottom.", "Keyboard users can focus a handle and use Up or Down to move a code. Select Prepare PDF to open the chosen sheet in a new tab, or Cancel to close the dialog."],{tab:'Presentations',action:'qr-selection',note:"PPT Slidedeck and Speaker Notes are selected and moved to the top. Other codes continue below the visible rows."});
add(5,'presentation-form','Edit presentation details','edit_engagement.php?id='+f.event,["Choose a saved speaker and enter the topic, date, time, duration, and expected attendance.", "Record actual attendance after the event. Zero is valid when nobody attended.", "Continue to Presentation Files & QR Codes below these fields to add PDF notes and a PowerPoint file.", "Save Changes saves the whole engagement form, including other edits on the page."],{focus:'.presentation-entry'});
add(5,'logistics','Review event logistics','view_engagement.php?id='+f.event,['Open Logistics to review the event address, materials, travel, compensation, and lodging.','Planning estimates describe arrangements; actual received amounts belong in Financial Closeout.','Keep the physical event location accurate for the map and presentation exports.'],{tab:'Logistics',focus:'#engagement-workspace'});
add(5,'lifecycle','Lifecycle and rescheduling','edit_engagement.php?id='+f.event,['Use Active, Postponed, Canceled, or Completed to describe the operational state.','Keep Work in Progress, Under Review, or Confirmed as the separate planning confidence.','Provide a cancellation reason. When rescheduling, link the replacement event from the same organization.'],{focus:'[name=lifecycle_status]'});
add(5,'statistics',"Review combined presentation QR activity",'short_links.php?presentation_id='+extra.presentation,["Open Combined Presentation Statistics from the presentation pane. Totals combine its QR codes, including historical visits to disabled and previous-speaker codes.", "Choose a UTC date range. Hover or tap the charts, or expand the data tables for exact daily, referrer, browser, country, and operating system counts.", "Clear Filters stays within the presentation. Back to Presentation returns to its pane. A person opening multiple codes contributes multiple visits."],{focus:'.short-link-report',note:'The chart uses fictional, seeded visit counts to illustrate the report.'});
add(5,'financial','Review financial closeout','view_engagement.php?id='+f.event,['Open Financials to see whether a report is open, a draft, or final.','Use Financial Closeout to enter giving/income, lodging, and travel actually received.','A draft does not enter finalized organization financial history.'],{tab:'Financials',focus:'#engagement-workspace'});
add(5,'closeout','Draft and finalize received amounts','close_engagement.php?id='+f.event,['Leave unknown draft amounts blank; enter zero only when nothing was received.','Resolve every task due on or before the last active presentation by marking it Completed. Canceled tasks still hold closeout.','Check the final-amount confirmation, then Finalize and close event when prerequisites are satisfied.','For a final report, use correction to update amounts while retaining the original close date.']);
add(5,"email-templates","Manage the email template library","email_templates.php",["Open Email Templates under Work in the sidebar, or Manage Email Templates in an engagement email.", "Search by name or subject. Select + New Email Template, a template name, or its Edit action.", "Archive removes a template from new messages. Open Archived and choose Restore to use it again.", "Only administrators can permanently delete an archived template after confirming access. Sent messages and history remain unchanged."],{"note": "Fictional records from the isolated template preview; no email was queued during capture."});
add(5,"email-template-editor","Add or edit reusable email text",'edit_email_template.php?id='+(f.email_template||1),["Enter a clear template name, a subject, and the starting plain-text message.", "Use event fields such as {{event_name}} in the text. The engagement routing marker is added automatically when composing.", "Existing templates can be edited too. Save Changes updates the template for future selections, leaving sent messages intact.", "If another session changed the template, preserve your edits, reload, and review the current version before saving."],{"note": "Fictional records from the isolated template preview; no email was queued during capture."});
add(5,"email-template-fields","Personalize fields and suggest recipients",'edit_email_template.php?id='+(f.email_template||1),["Expand Personalize with event fields. Place the cursor in the subject or message, then select a field button.", "Presentation schedule is available in the message only. Speaker names inserts text; it does not select recipients.", "Choose suggested event contact roles. Leave all clear to choose contacts when composing. Lower Display order numbers appear first.", "Save the template. Open an engagement email, choose it, and review the filled text and recipients before queuing."],{"focus": ".email-template-field-help", "action": "email-fields", "note": "Fictional records from the isolated template preview; no email was queued during capture."});
add(6,'organizations','Browse organizations','organizations.php?q=Cedar',['Search by organization details or active contact information.','Review location, active contacts, last giving, and lifetime giving.','Use Active/Archived, sorting, and Records per page to manage a longer directory.']);
add(6,'organization','Review relationship history','view_organization.php?id='+f.org,['Use Activity for organization-level Chron.','Switch to Contacts, Engagements, Tasks, or Financials for related information.','Use Edit Organization to maintain details and add or move contacts.']);
add(6,'organization-financial','Read organization financial history','view_organization.php?id='+f.org,['Open Financials for finalized giving, lodging, travel, and event reports.','Draft closeout amounts do not affect these totals.','Open an event report for the underlying figures and correction history.'],{tab:'Financials',focus:'#organization-financials',note:'Amounts are fictional examples.'});
add(6,'organization-form','Organization identity and addresses','edit_organization.php?id='+f.org,['Only the organization name is required. Add affiliation, distinctives, contact channels, and notes when known.','Choose country before state or province. US and Canadian regions use dropdowns; other countries accept typed regions.','Use Same as Physical Address when mailing details match.']);
add(6,'contacts','Browse contacts','contacts.php?q=Parker',['Search by person or organization, sort the list, and adjust Records per page.','Open a contact to review history and affiliations; the row action icons remain available.','Administrators can select aligned checkboxes and choose Delete selected. Select all applies only to this page; Clear selection starts over.','Review the selected names and related data, unlock if required, then confirm the Are you sure? dialog.']);
add(6,'contact','Read a contact record','view_contact.php?id='+f.contact,['Check name, role, email, phone, photo, and organization links.','Keep person-specific conversations in this contact\'s Chron.','Create follow-up work here to retain the relationship context.']);
add(6,'contact-form','Maintain affiliations and a photo','edit_contact.php?id='+f.contact,['Enter names and contact channels; an organization is optional.','Set the primary organization role and add additional organization affiliations with their own roles.','Use Other with Describe Other Role for a custom title.','Upload a JPEG, PNG, or WebP photo up to 5 MB and save. Create Organization preserves the contact draft.']);
add(6,'speakers','Find a saved speaker','speakers.php?q=Alex',['Search by name, email, or phone; use Name to reverse alphabetical order.','Open a profile, or use New Speaker to create one. Editors and administrators can maintain speaker details.','Administrators can use the individual Delete icon or select multiple speakers and choose Delete selected.','Referenced speakers are protected; only unused profiles can be permanently deleted after admin unlock and confirmation.']);
add(6,'speaker','Speaker profile and resources','view_speaker.php?id='+f.speaker,['Review the reusable speaker identity, biography, and audience links.','Open Statistics to review activity across the speaker\'s presentations.','Edit the profile to maintain shared details. The written biography and Bio URL serve different purposes.']);
add(6,'speaker-links','Edit standard and custom resource links','edit_speaker.php?id='+f.speaker,['Add full web addresses for audience resources.','Choose Add Custom Link, provide its name and URL, and save the speaker.','New links receive separate codes on existing and future presentations.','Removing or renaming a profile link preserves already-published codes. Manage an individual code in Statistics.'],{focus:'#speaker-links-heading'});
add(7,"tasks","Work the queue","tasks.php?owner=me",["Choose My work, Everyone’s work, or Unassigned work, then a due-date/status filter.", "Read the date and its timing label: overdue, Due today, Due tomorrow, or Upcoming. Dates use the application time zone.", "Select the task to edit it, or the green check-mark to review completion. Archive preserves its status and details; use Archived to restore it."],{});
add(7,'task-form','Edit a task','edit_task.php?id='+f.task,['Write a concrete title and notes.','Search at least three characters and select the intended related record, or use general work.','Set assignee, due date, priority, and status. Waiting work should name the person or decision it needs.','Save task to persist the change.']);
add(7,'duplicate-task','Duplicate a task to another event','add_task.php?duplicate_from='+f.task,['Choose Duplicate to Another Event from the task editor.','Search events and select a destination different from the source event.','Review copied title and notes, ownership, due date, priority, and status before saving.','The original task remains unchanged.']);
add(7,'standard-tasks','Manage reusable event checklists','standard_tasks.php',['Open Standard Event Tasks from the Work Queue.','Create or edit the content, priority, display order, and offset from event start or end.','Changes affect generation; existing task content is independently editable.','The required financial reminder is fixed at one week after event end.']);
add(7,'standard-form',"Schedule a standard task for existing engagements",'add_standard_task.php',["Enter the reusable title and notes above the Scheduling section. Choose priority, date anchor, day offset, and display order.", "Administrators can check Also add this task to all active, open engagements before Add standard task. Editors can maintain definitions but cannot use bulk generation.", "This adds the task to unarchived engagements with an Active lifecycle and open financial closeout. Copies use the date rule and go to the active Caller, or to the administrator if none is assigned.", "On a saved definition, administrators can use Add to Active, Open Engagements. Existing copies, including completed or canceled tasks, are kept without duplication."],{action:'standard-generation',focus:'.form-section:has(#standard-task-priority)',note:'The option is selected for illustration; the form was not submitted.'});
add(8,'chron','Add a Chron entry','view_engagement.php?id='+f.event,['Use Add Chron Log Entry to record a decision without opening the complete edit form.','Include the context, outcome, and agreed next step.','Save the entry; its author and time appear in reverse chronological history.'],{action:'chron'});
add(8,'email',"Choose To, Cc, Bcc, and a self-copy",'compose_engagement_email.php?id='+f.event,["Choose an active template or Custom message, then select assigned contacts and optional speakers. Changing templates preserves selected speakers.", "Choose To, Cc, or Bcc on each selected recipient card. To and Cc addresses are visible to all recipients; Bcc addresses stay hidden.", "Under Send yourself a copy, choose Cc me or Bcc me for your account email. Matching addresses receive one copy and must use the same recipient type.", "Review the subject, message, and optional brief before Queue Email. Check Correspondence for the delivery result."],{action:'email-recipients',note:'Fictional recipient selections and a self-copy; no email was queued during capture.'});
add(8,'email-message','Review the message and brief','compose_engagement_email.php?id='+f.event,['Edit the plain-text message for the event.','Expand Preview Event Brief to inspect the optional share-safe information before including it.','The event marker is maintained for routing. A sent checklist email does not complete its related task automatically.'],{focus:'#body'});
add(8,"inbox","Review copied inbound email",'inbound_mail.php',["Open Inbox in the sidebar. Use Needs review, Pending, Processing, Failed, Processed, Rejected, or All to choose a queue.", "Search by subject, sender, or message content. Change Order or use the queue pages when needed. Needs review starts oldest first.", "On a wide screen, the message list is on the left, the reader is in the middle, and the filing panel is on the right.", "Select a message to read it. Search messages stays visible at a consistent vertical position. On a phone, use Back to messages to return to the queue."],{"shell": true});
add(8,"inbound-message","Read a message and choose its Chron Logs",'inbound_mail.php?id='+f.mail,["Read the sender, subject, and message. Expand Message details for recipients, sent time, and attachment names; open Routing details for matching reasons.", "Review the reason in the right-hand filing panel. Choose the intended Contact, Organization, or Inquiry suggestions when available. Scroll down to search and select an active Engagement.", "Check the selected Chron log count, then choose Save to Chron logs. Processed messages show Message status and Saved to Chron so you can review their destinations.", "Find matches again checks routing after record corrections. Other actions contains Reject message. Administrators can expand Manage retained email below the reader to purge the retained source after confirmation."],{"shell": true, "focus": "#inbound-queue-search"});
add(9,'map','Locate engagements','map.php?date_from=2026-09-10&date_to=2026-09-14',['Filter the date window, lifecycle, and confirmation state.','Select a pin for event context; use Fit visible pins after filtering.','Use the list views to find missing addresses, pending lookups, or unlocated records, then Edit location.'],{focus:'.map-shell'});
add(9,'map-pin','Confirm an event pin','map_pin.php?id='+f.event,['Check the written event address before changing a pin.','Zoom and click the map, drag the pin, or enter latitude and longitude.','Check the venue confirmation, then Save confirmed pin. Use automatic lookup clears an override.','A later address change requires checking the pin again.'],{focus:'#pin-editor-map'});
add(9,'calendar','Browse the month calendar','view_calendar.php',['Use Previous, Next, or Today to navigate months.','Choose Events, My Tasks, All Tasks, Birthdays, or Everything.','Tasks need an active status and a due date to appear.','Click an event, task, or birthday to open its record. The rose Today cell is separate from event/task colors.']);
add(9,'subscription','Private calendar subscriptions','view_calendar.php',['Name each device or service, and choose Events, Presentations, My Active Work, All Active Work, and/or Birthdays (from Contacts).','Create the link, copy its private URL immediately, and add it in the calendar application as a subscribed calendar.','Treat the URL as an access credential for its selected content, including task information when work is selected.','Revoke one device link when no longer needed; purge revoked records separately.'],{focus:'#calendar-subscriptions-title'});
add(10,'profile','Profile and daily work digest','profile.php',['Maintain name, email, phone, and optional picture.','Verify an email change to re-enable recovery and the digest.','Choose digest time and days, or turn the digest off.','Resending verification preserves the current profile draft and chosen photo.']);
add(10,'security','Manage account security','two_factor_settings.php',['Enroll or replace the authenticator as needed. Administrators must use 2FA.','Change your password with the current password and required factor.','Generate fresh recovery codes when needed; save them securely because each works once.','Administrator resets and password changes can invalidate other sessions.']);
add(10,'setup','Start authenticator replacement','setup_2fa.php',['Confirm your password and, when replacing an enrolled factor, your current authentication code.','Scan the enrollment QR code in an authenticator or enter its setup key.','Enter the generated six-digit code to verify enrollment, then store the recovery codes.'],{note:'Only the initial confirmation screen is illustrated. Enrollment secrets and recovery codes are intentionally absent.'});
add(11,'mattermost','Connect MOED and Mattermost','mattermost.php',['When configured, generate a one-time linking code here and run /moed connect CODE in Mattermost.','Use /moed today, /moed tasks, and event search/show for private context.','Editors and administrators may link channels and review task, Chron, and email actions.','Unlink an account here to revoke its Mattermost command access.'],{note:'The disposable preview is not connected to Mattermost. The chapter explains the configured plugin workflow; this screen shows its setup prerequisite.'});
add(12,'users','Review users and access state','users.php',['Review the identity, account state, 2FA, contact details, and Daily Digest days on each card.','Use the lower action bar: Edit user and security controls are grouped separately from account access and deletion.','Amber Deactivate suspends an active account; red Delete user permanently removes an inactive or invited account after confirmation.','Only eligible accounts have deletion checkboxes. Individual Delete user remains available alongside Delete selected.']);
add(12,'invite','Invite a new user','register.php',['Confirm administrator access, then choose a unique username, email address, and role.','Review the recipient and access level before sending the invitation.','The recipient creates their own password through the activation link. Configure digest preferences from the user editor afterward.'],{elevated:true,note:'This form is shown without submitting an invitation.'});
add(12,"elevation","Confirm administrator access","admin_elevation.php",["Open a locked sensitive action or Unlock Sensitive Actions on Users.", "Enter the administrator password and a fresh authenticator or unused recovery code.", "Unlock Sensitive Actions returns to the requested page and starts a five-minute countdown for this signed-in session."],{});
add(12,'audit','Inspect the audit trail','audit_log.php',['Filter by category, search text, date range, and exact IP address.','Review actor, action, affected record, and local/UTC timestamps.','Individual audit records cannot be edited or removed through ordinary record controls.']);
add(12,'retention','Preview audit retention','audit_log.php?tab=retention',['Open the retention panel and choose the number of days to keep.','Preview the UTC cutoff and affected count before pruning.','Fresh administrator confirmation, the exact PRUNE phrase, and the final in-app confirmation are required.'],{focus:'#audit-retention-title'});
add(12,"backup","Export an encrypted backup with uploaded files","database_maintenance.php",["Open Database. The encrypted snapshot includes application records, PDF notes, PowerPoint files, and uploaded portraits.", "Enter your administrator password and a fresh factor. Choose and confirm a unique backup password of at least 16 characters, then Encrypt and Download Backup.", "Keep the page open while the export runs. Check the success message, Last backup created, and browser Downloads for completion.", "Keep the complete .dnrbackup file, its password, and the separate 2FA key securely backed up. Ask the deployment operator to restore records and files together."],{"note": "The export form is shown before submission; no backup was created during screenshot capture."});
add(12,'operations','Review operational health','operations.php',['Inspect task backlog, geocoding queues, mail review/failures, and authentication failures.','Check migration readiness and the latest recorded encrypted backup.','Follow the linked application view for work you can resolve; give deployment faults to the operator.']);
add(13,'manual-search','Find help quickly','help.php',['Search the online manual for a term such as financial closeout.','Use Clear to return to all chapters.','In this PDF use the contents, bookmarks, related-topic links, topic finder, or your reader\'s text search.'],{action:'search'});
add(5,'presentation-exports',"Copy or export a presentation brief",'view_engagement.php?id='+f.event,["In Presentations, expand Export Presentation at the bottom of the card.", "Copy Text produces plain text; Copy MD produces Markdown. View PDF opens the branded presentation brief.", "View QR Codes PDF opens a selection dialog. Choose and order the codes, then select Prepare PDF to view, save, or print the landscape sheet."],{tab:'Presentations',action:'exports',focus:'.presentation-export'});
add(5,'link-controls','Change an existing QR destination','short_links.php?id='+extra.link,['Review the specific code and its activity.','Edit Destination and save to redirect an already-published resource code without changing its image.','Clear Link enabled and save to stop that code from opening its destination.','For Speaker Notes and PPT Slidedeck, replace the file on the presentation; its destination is managed automatically.'],{focus:'[name=target_url]'});
add(5,'reset-statistics','Reset one presentation\'s statistics','reset_presentation_stats.php?presentation_id='+extra.presentation,['Administrators open Reset Presentation Statistics on the presentation card.','Confirm the exact presentation and obtain fresh administrator access.','Reset Statistics to Zero permanently clears all dates and all its links, including disabled links and previous speakers.','Codes, destinations, uploaded files, and other presentations stay intact; new visits start at zero.'],{note:'The reset review screen is illustrated; no statistics were deleted.'});
add(5,'closeout-amounts','Enter actual receipts','close_engagement.php?id='+f.event,['Enter known Giving/income, Lodging, and Travel received amounts.','The draft total shows the entered values and completion state.','Save draft while prerequisites remain unresolved. Enter all three amounts and confirm they are final before finalizing.'],{focus:'.closeout-form'});
add(5,'final-report','Read a finalized financial report','view_engagement.php?id='+extra.past_event,['Open Financials on the completed event to see its final received amounts.','The report contributes to the organization\'s finalized financial history.','Use the correction control when an amount needs to change; the original closer and close date are retained.'],{tab:'Financials',focus:'#engagement-workspace',note:'This completed report contains fictional amounts.'});
add(12,"edit-user","Edit user profile and digest preferences",'edit_user.php?id='+extra.target_user,["Unlock sensitive administrator actions, then select Edit user on the Users page.", "Edit first/last name, country-aware phone, username, and role. Replace or remove the profile picture; JPEG, PNG, and WebP uploads allow up to 5 MB.", "Review daily digest settings and save. Ordinary profile edits preserve a paused digest.", "The account holder changes recovery email through the separate verification flow in My Profile."],{"elevated": true, "note": "Fictional Casey Taylor account. Scroll to review the remaining digest controls and Save changes."});
add(9,'calendar-agenda','Use the daily agenda on a phone','view_calendar.php?day=2026-09-09',['On a narrow screen, Calendar presents a daily agenda.','Use the day arrows or Today to change dates and the content selector to focus the list.','Open an event, task, or contact birthday to continue with that record.'],{action:'mobile-calendar',shell:true});
add(10,'recovery-email','Verify a new recovery email','profile.php',['Open Change Recovery Email and enter the new email, current password, and a fresh authenticator code when required.','Select Verify New Email Address, then follow the verification message at the new address.','Your old address stays active until verification. The change signs out all sessions and pauses the digest.','Cancel a pending change or resend verification from My Profile if needed.'],{focus:'#recovery-email-heading'});
add(10,'login','Sign in to MOED','login.php',['Enter the username and your private password.','Complete the authenticator or recovery-code challenge if your account uses 2FA.','If prompted to change a temporary password or enroll an authenticator, complete that step before continuing.','Use the account menu to sign out when finished.'],{anonymous:true,shell:true});
add(10,'forgot-password','Request password recovery','recover_password.php',['Choose Forgot your password? on sign-in.','Enter the verified email address on the active account and request a reset link.','Follow the single-use link to choose a new password. Existing sessions are invalidated.','If no verified email or recovery factor is available, contact an administrator.'],{anonymous:true,shell:true});

(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const context=await browser.newContext({storageState:process.env.DNR_MANUAL_SESSION || path.join(root,'tmp/pdfs/manual-session.json'),viewport:{width:1280,height:940},deviceScaleFactor:1.5,reducedMotion:'reduce'});
 const page=await context.newPage();page.setDefaultTimeout(30000);
 let elevatedAt=0;
 function freshCode(credentials){
  const crypto=require('node:crypto');let bits='';for(const ch of credentials.totp_secret.toUpperCase().replace(/=+$/,''))bits+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(ch).toString(2).padStart(5,'0');
  const key=Buffer.from(bits.match(/.{8}/g).map(b=>parseInt(b,2)));const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=crypto.createHmac('sha1',key).update(counter).digest();return ((h.readUInt32BE(h[19]&15)&0x7fffffff)%1000000).toString().padStart(6,'0');
 }
 // The preview contains sample data only. Public CDN scripts are not needed for captures.
 await page.route(/https:\/\/(cdnjs|cdn\.jsdelivr|fonts\.google|unpkg)/,r=>r.abort());
 await page.goto(base+'/help.php',{waitUntil:'domcontentloaded',timeout:45000});
 if(page.url().includes('login.php')){
  const credentials=JSON.parse(fs.readFileSync(process.env.DNR_MANUAL_CREDENTIALS));
  await page.locator('[name=username]').fill(credentials.username);await page.locator('[name=password]').fill(credentials.password);await page.locator('button[type=submit]').first().click();
  if(page.url().includes('verify_2fa.php')){await page.locator('[name=authentication_code]').fill(freshCode(credentials));await page.locator('button[type=submit]').first().click();}
  if(/login.php|verify_2fa.php/.test(page.url()))throw Error('Preview sign-in failed');
  await context.storageState({path:process.env.DNR_MANUAL_SESSION || path.join(root,'tmp/pdfs/manual-session.json')});
 }
 const only=process.env.DNR_MANUAL_ONLY?.split(',');
 for(const s of shots){if(only&&!only.includes(s.id))continue;
  try{
   await page.setViewportSize({width:1280,height:940});
   if(s.anonymous)await context.clearCookies();
   await page.addInitScript(()=>localStorage.setItem('theme','light'));
   if(s.elevated&&Date.now()-elevatedAt>240000){
    await page.goto(base+'/admin_elevation.php',{waitUntil:'domcontentloaded',timeout:45000});
    const credentials=JSON.parse(fs.readFileSync(process.env.DNR_MANUAL_CREDENTIALS));
    const code=freshCode(credentials);
    await page.locator('[name=admin_password]').fill(credentials.password);await page.locator('[name=admin_code]').fill(code);await page.getByRole('button',{name:'Unlock Sensitive Actions'}).click();
    if(page.url().includes('admin_elevation.php'))throw Error('Administrator confirmation failed');elevatedAt=Date.now();
   }
   const response=await page.goto(base+'/'+s.route,{waitUntil:'domcontentloaded',timeout:45000});
   if(response.status()!==200 || (!s.anonymous&&page.url().includes('login.php')))throw Error('Page unavailable: '+response.status()+' '+page.url());
   await page.evaluate(()=>document.documentElement.classList.remove('dark-mode'));
   await page.waitForTimeout(350);
   if(s.id==='manual'){
    const chapters=await page.locator('[data-manual-section]').evaluateAll(es=>es.map(e=>({id:e.id,title:e.querySelector('h2').textContent,html:e.innerHTML,keywords:e.dataset.keywords})));
    fs.writeFileSync(path.join(out,'online-chapters.json'),JSON.stringify(chapters,null,2)+'\n');
   }
   if(s.tab)await page.getByRole('tab',{name:s.tab,exact:true}).click();
   if(s.action==='email-fields')await page.getByText('Personalize with event fields',{exact:true}).click();
   if(s.action==='dark')await page.locator('[data-theme-toggle]').last().click();
   if(s.action==='roles')await page.locator('.role-preview-disclosure').evaluate(e=>e.open=true);
   if(s.action==='mobile'){await page.setViewportSize({width:390,height:844});await page.locator('[data-nav-toggle]').click();}
   if(s.action==='mobile-calendar')await page.setViewportSize({width:390,height:844});
   if(s.action==='email-recipients'){await page.locator('[data-select-all-recipients]').click();const contacts=page.locator('select[name^="recipient_types[contact:"]');for(let i=0;i<await contacts.count();i++)await contacts.nth(i).selectOption(i===0?'to':'cc');const speakers=page.locator('select[name^="recipient_types[speaker:"]');for(let i=0;i<await speakers.count();i++)await speakers.nth(i).selectOption('bcc');if(await page.locator('#sender-copy').isEnabled())await page.locator('#sender-copy').selectOption('bcc');}
   if(s.action==='standard-generation'){await page.locator('#standard-task-title').fill('Review presentation resources');await page.locator('#standard-task-details').fill('Check the uploaded speaker notes and audience resource links.');await page.locator('#standard-task-priority').selectOption('high');await page.locator('#standard-task-offset').fill('-3');await page.locator('#standard-task-order').fill('62');await page.locator('#generate-existing-engagements').check();}
   if(s.action==='qr-selection'){await page.getByText('Export Presentation',{exact:true}).first().click();await page.getByRole('link',{name:'View QR Codes PDF',exact:true}).first().click();await page.getByRole('dialog').getByRole('checkbox',{name:'Select all',exact:true}).uncheck();for(const label of ['Speaker Notes','PPT Slidedeck']){await page.getByRole('dialog').getByRole('checkbox',{name:label,exact:true}).check();await page.getByRole('button',{name:'Reorder '+label,exact:true}).press('Home');}}
   if(s.action==='exports')await page.locator('.presentation-export').first().evaluate(e=>e.open=true);
   if(s.action==='search')await page.locator('[data-manual-search]').fill('financial closeout');
   if(s.action==='chron'){const button=page.getByText('Add Chron Log Entry',{exact:true}).first();await button.click();}
   if(s.focus){const target=page.locator(s.focus).first();if(await target.count())await target.evaluate(e=>{e.scrollIntoView({block:'start'});window.scrollBy(0,-20);});else throw Error('Missing focus '+s.focus);}
   if(s.id==='map'||s.id==='map-pin')await page.waitForTimeout(2200);
   await page.waitForTimeout(250);
   const body=await page.locator('body').innerText();
   if(/unexpected error|Fatal error:/.test(body))throw Error('Application error');
   fs.mkdirSync(path.join(root,'tmp/pdfs/screens'),{recursive:true});
   fs.writeFileSync(path.join(root,'tmp/pdfs/screens',s.id+'.txt'),body);
   fs.writeFileSync(path.join(root,'tmp/pdfs/screens',s.id+'.html'),await page.content());
   s.file='screenshots/'+s.id+'.png';s.captured_at=new Date().toISOString().slice(0,10);
   const view=page.viewportSize();
   const clip=s.shell?{x:0,y:0,width:view.width,height:view.height}:{x:270,y:0,width:1010,height:850};
   const footer=await page.locator('.app-footer').count()?await page.locator('.app-footer').boundingBox():null;
   if(footer&&footer.y>240&&footer.y<clip.height)clip.height=Math.floor(footer.y-10);
   await page.screenshot({path:path.join(out,s.file),clip,animations:'disabled'});
   if(!s.anonymous)await context.storageState({path:process.env.DNR_MANUAL_SESSION || path.join(root,'tmp/pdfs/manual-session.json')});
   console.log('Captured '+s.id);
  }catch(e){console.error('FAILED '+s.id+': '+e.message);s.error=e.message;}
 }
 const old=fs.existsSync(path.join(out,'screenshots.json'))?JSON.parse(fs.readFileSync(path.join(out,'screenshots.json'))):[];
 if(only)for(const s of shots)if(!only.includes(s.id))Object.assign(s,old.find(o=>o.id===s.id)||{});
 const combined=[...shots,...old.filter(previous=>!shots.some(current=>current.id===previous.id))];
 fs.writeFileSync(path.join(out,'screenshots.json'),JSON.stringify(combined,null,2)+'\n');
 await browser.close();
 if(shots.some(s=>s.error))process.exitCode=1;
})();
