Foreground yes
User clamav
TCPSocket 3310
TCPAddr 0.0.0.0
LocalSocket /tmp/clamd.sock
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
LogTime yes
LogFile /tmp/clamd.log
PidFile /tmp/clamd.pid
StreamMaxLength 500M
MaxFileSize 500M
MaxScanSize 1000M
MaxScanTime 120000
MaxRecursion 16
MaxFiles 10000
MaxThreads 1
MaxQueue 4
ReadTimeout 120
CommandReadTimeout 10
SendBufTimeout 1000
AlertExceedsMax yes
AlertEncrypted yes
ScanArchive yes
ScanPDF yes
ScanOLE2 yes
ConcurrentDatabaseReload no
SelfCheck 600
